# Generated by Django 5.0 on 2023-12-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationhistory',
            name='reservation',
        ),
    ]
