# Generated by Django 4.2.7 on 2023-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fieldsRented',
            field=models.ManyToManyField(to='registration.fieldrenthistory'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='clubPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='club_photos'),
        ),
    ]
