# Generated by Django 4.2.7 on 2023-12-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_client_fieldsrented_alter_tenant_clubphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldrenthistory',
            name='reservation',
        ),
        migrations.AddField(
            model_name='tenant',
            name='clubApertureTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de apertura'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='clubClosureTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de cierre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fieldsRented',
            field=models.ManyToManyField(related_name='clients', to='registration.fieldrenthistory'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
