# Generated by Django 5.0 on 2023-12-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_rename_maxplayers_field_playersperside_and_more'),
        ('registration', '0005_fieldrenthistory_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAtReservation', models.DateTimeField()),
                ('dateToReservate', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed')], max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.client')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.field')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='reservationHistory',
            field=models.ManyToManyField(related_name='clients', to='registration.reservationhistory'),
        ),
    ]
