# Generated by Django 5.0 on 2023-12-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_reservationhistory_client_reservationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
