# Generated by Django 5.0 on 2023-12-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_reservationhistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
