# Generated by Django 5.0 on 2023-12-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_usuarioprofile_borndate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioprofile',
            name='role',
            field=models.CharField(default='client', max_length=100, verbose_name='Crear cuenta como club'),
        ),
    ]
