# Generated by Django 4.2.7 on 2023-12-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='category',
        ),
        migrations.RemoveField(
            model_name='field',
            name='rentedBy',
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='fieldPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='field_photos'),
        ),
        migrations.AddField(
            model_name='field',
            name='groundType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='maxPlayers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='FieldCategory',
        ),
    ]
