# Generated by Django 4.2.7 on 2023-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_remove_field_category_remove_field_rentedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='maxPlayers',
            new_name='playersPerSide',
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='groundType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
