# Generated by Django 5.0 on 2023-12-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_alter_field_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, default='not defined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='groundType',
            field=models.CharField(blank=True, choices=[('Pasto sintético', 'Pasto sintético'), ('Pasto real', 'Pasto real'), ('Cemento', 'Cemento'), ('Arcilla', 'Arcilla')], default='Pasto sintético', max_length=100),
        ),
    ]
