# Generated by Django 5.0 on 2023-12-18 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_alter_field_description_alter_field_groundtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='field',
            name='opening_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
    ]
