# Generated by Django 4.2.7 on 2023-12-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='field_rent_history',
        ),
    ]
