# Generated by Django 4.2.7 on 2023-12-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_field_rent_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateAtReservation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateToReservate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
    ]
