# Generated by Django 5.0 on 2023-12-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_court_reservation_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='court',
        ),
        migrations.DeleteModel(
            name='Court',
        ),
    ]
